name 'puppetlabs-rabbitmq'
version '2.0.2'

author 'puppetlabs'
license 'Apache'
project_page 'http://github.com/puppetlabs/puppetlabs-rabbitmq'
source 'git://github.com/puppetlabs/puppetlabs-rabbitmq.git'
summary 'RabbitMQ Puppet Module'
description 'This module manages RabbitMQ. Tested on Debian/Ubuntu'
dependency 'puppetlabs/stdlib', '>=2.0.0'
dependency 'puppetlabs/apt', '>=0.0.3'
